# Generated by Django 5.2.2 on 2025-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_school_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
